### ISSUE TITLE
Features and Project Plan

### ISSUE THREAD

**Issue by alyssar60819** [nsk1207/projectNASH#1]
- [x] Plan and format games
- [x] Get local to work for all
- [x] Feature 1 - Username Login (Haseeb)
- [x] Feature 2 - Register (Nathan) 
- [ ] Feature 3 - Leader Board (Haseeb)
- [x] Feature 4 - Arrow Game with Randomization (Alyssa)
- [x] Feature 5 - Color Game with Randomization (Alyssa)
- [x] Feature 6 (kinda) - drop down menu (nathan)
