### ISSUE TITLE
Progress Tracker for "Trivia!"

### ISSUE THREAD

**Issue by h4seeb-cmd** [nsk1207/projectNASH#14]
### Actual End User Features:
- [x] Home Screen 
- [x] Questions
- [x] Score System
- [x] ~~Life System~~ (Redacted)
- [x] Win Screen?
- [x] Lose Screen

### How To Get There?? Possible Solutions:
- [x] Use RapidAPI to pull unlimited questions??
- [x] Maybe have a list of questions, then randomize question list??? I could do this by using the random library in python to randomize the indexes in a list. Then display whatever number was picked. It would use lists and procedures, which would be great for collegeboard.
- [x] For life and score system, simply make a variable. Depending on the answer chosen, it either adds +1 score or -1 life. For this, I will simply just run basic if statements.

### Scrapped Ideas:
In general, I think that the leaderboard idea is bust. The timings are really tight, and it would be a LOT of extra work for not a whole lot of payoff. We would be better off improving our games.

### Deadline:
I would want at least the questions done, along with the life system.  This would give me some code to stand on. (COMPLETE)

### Update:
I scrapped the Life System, as I set the quiz to a set number of questions using a system similar to Rapid API. I plan to make my own question API this week, and from there I can develop my own algorithm to randomize them.

### Things to Debug (As of 2/13/23)
- [x] Touch up on CSS, maybe add cool animations.
- [x] Not much of a debugging thing, but add the game onto the group repo.  

# To Update By Spring Break:
- [ ] Make the UI cleaner
- [ ] Remove BS bugs that hinder the UX
- [ ] General QoL improvements

### How I will achieve this and what this stuff entails:
For the UI, it's still pretty janky. There are not a whole lot of animations to smooth the buttons, so it's very sharp and it feels very janky. The text is also very mis-sized. This is a fairly easy fix and it would just be working on the CSS/SASS.

For the general bug fixing/QoL, there are some sort of hidden bugs that hinder efficiency and UX. For one, questions have an odd tendency to repeat after 3 questions. Other than that, everything is pretty airtight, I just need to look for ways to decrease the time and space complexity of the program.
